// Code generated by template.go DO NOT EDIT.

package currying

type Func0_1[R1 any] func() R1

func (f Func0_1[R1]) Reverse() Func0_1[R1] {
	return func() R1 {
		return f()
	}
}

func Make0to1[R1 any](f func() R1) Func0_1[R1] {
	return func() R1 {
		return f()
	}
}

type Func0_2[R1, R2 any] func() (R1, R2)

func (f Func0_2[R1, R2]) Reverse() Func0_2[R1, R2] {
	return func() (R1, R2) {
		return f()
	}
}

func Make0to2[R1, R2 any](f func() (R1, R2)) Func0_2[R1, R2] {
	return func() (R1, R2) {
		return f()
	}
}

type Func0_3[R1, R2, R3 any] func() (R1, R2, R3)

func (f Func0_3[R1, R2, R3]) Reverse() Func0_3[R1, R2, R3] {
	return func() (R1, R2, R3) {
		return f()
	}
}

func Make0to3[R1, R2, R3 any](f func() (R1, R2, R3)) Func0_3[R1, R2, R3] {
	return func() (R1, R2, R3) {
		return f()
	}
}

type Func1[T1 any] func(v1 T1)

func (f Func1[T1]) Apply1(v1 T1) Func0 {
	return func() {
		f(v1)
	}
}

func (f Func1[T1]) Reverse() Func1[T1] {
	return func(v1 T1) {
		f(v1)
	}
}

func Make1[T1 any](f func(T1)) Func1[T1] {
	return func(v1 T1) {
		f(v1)
	}
}

type Func1_1[T1, R1 any] func(v1 T1) R1

func (f Func1_1[T1, R1]) Apply1(v1 T1) Func0_1[R1] {
	return func() R1 {
		return f(v1)
	}
}

func (f Func1_1[T1, R1]) Reverse() Func1_1[T1, R1] {
	return func(v1 T1) R1 {
		return f(v1)
	}
}

func Make1to1[T1, R1 any](f func(T1) R1) Func1_1[T1, R1] {
	return func(v1 T1) R1 {
		return f(v1)
	}
}

type Func1_2[T1, R1, R2 any] func(v1 T1) (R1, R2)

func (f Func1_2[T1, R1, R2]) Apply1(v1 T1) Func0_2[R1, R2] {
	return func() (R1, R2) {
		return f(v1)
	}
}

func (f Func1_2[T1, R1, R2]) Reverse() Func1_2[T1, R1, R2] {
	return func(v1 T1) (R1, R2) {
		return f(v1)
	}
}

func Make1to2[T1, R1, R2 any](f func(T1) (R1, R2)) Func1_2[T1, R1, R2] {
	return func(v1 T1) (R1, R2) {
		return f(v1)
	}
}

type Func1_3[T1, R1, R2, R3 any] func(v1 T1) (R1, R2, R3)

func (f Func1_3[T1, R1, R2, R3]) Apply1(v1 T1) Func0_3[R1, R2, R3] {
	return func() (R1, R2, R3) {
		return f(v1)
	}
}

func (f Func1_3[T1, R1, R2, R3]) Reverse() Func1_3[T1, R1, R2, R3] {
	return func(v1 T1) (R1, R2, R3) {
		return f(v1)
	}
}

func Make1to3[T1, R1, R2, R3 any](f func(T1) (R1, R2, R3)) Func1_3[T1, R1, R2, R3] {
	return func(v1 T1) (R1, R2, R3) {
		return f(v1)
	}
}

type Func2[T1, T2 any] func(v1 T1) func(v2 T2)

func (f Func2[T1, T2]) Apply1(v1 T1) Func1[T2] {
	return f(v1)
}

func (f Func2[T1, T2]) Apply2(v1 T1, v2 T2) Func0 {
	return func() {
		f(v1)(v2)
	}
}

func (f Func2[T1, T2]) Reverse() Func2[T2, T1] {
	return func(v2 T2) func(v1 T1) {
		return func(v1 T1) {
			f(v1)(v2)
		}
	}
}

func Make2[T1, T2 any](f func(T1, T2)) Func2[T1, T2] {
	return func(v1 T1) func(v2 T2) {
		return func(v2 T2) {
			f(v1, v2)
		}
	}
}

type Func2_1[T1, T2, R1 any] func(v1 T1) func(v2 T2) R1

func (f Func2_1[T1, T2, R1]) Apply1(v1 T1) Func1_1[T2, R1] {
	return f(v1)
}

func (f Func2_1[T1, T2, R1]) Apply2(v1 T1, v2 T2) Func0_1[R1] {
	return func() R1 {
		return f(v1)(v2)
	}
}

func (f Func2_1[T1, T2, R1]) Reverse() Func2_1[T2, T1, R1] {
	return func(v2 T2) func(v1 T1) R1 {
		return func(v1 T1) R1 {
			return f(v1)(v2)
		}
	}
}

func Make2to1[T1, T2, R1 any](f func(T1, T2) R1) Func2_1[T1, T2, R1] {
	return func(v1 T1) func(v2 T2) R1 {
		return func(v2 T2) R1 {
			return f(v1, v2)
		}
	}
}

type Func2_2[T1, T2, R1, R2 any] func(v1 T1) func(v2 T2) (R1, R2)

func (f Func2_2[T1, T2, R1, R2]) Apply1(v1 T1) Func1_2[T2, R1, R2] {
	return f(v1)
}

func (f Func2_2[T1, T2, R1, R2]) Apply2(v1 T1, v2 T2) Func0_2[R1, R2] {
	return func() (R1, R2) {
		return f(v1)(v2)
	}
}

func (f Func2_2[T1, T2, R1, R2]) Reverse() Func2_2[T2, T1, R1, R2] {
	return func(v2 T2) func(v1 T1) (R1, R2) {
		return func(v1 T1) (R1, R2) {
			return f(v1)(v2)
		}
	}
}

func Make2to2[T1, T2, R1, R2 any](f func(T1, T2) (R1, R2)) Func2_2[T1, T2, R1, R2] {
	return func(v1 T1) func(v2 T2) (R1, R2) {
		return func(v2 T2) (R1, R2) {
			return f(v1, v2)
		}
	}
}

type Func2_3[T1, T2, R1, R2, R3 any] func(v1 T1) func(v2 T2) (R1, R2, R3)

func (f Func2_3[T1, T2, R1, R2, R3]) Apply1(v1 T1) Func1_3[T2, R1, R2, R3] {
	return f(v1)
}

func (f Func2_3[T1, T2, R1, R2, R3]) Apply2(v1 T1, v2 T2) Func0_3[R1, R2, R3] {
	return func() (R1, R2, R3) {
		return f(v1)(v2)
	}
}

func (f Func2_3[T1, T2, R1, R2, R3]) Reverse() Func2_3[T2, T1, R1, R2, R3] {
	return func(v2 T2) func(v1 T1) (R1, R2, R3) {
		return func(v1 T1) (R1, R2, R3) {
			return f(v1)(v2)
		}
	}
}

func Make2to3[T1, T2, R1, R2, R3 any](f func(T1, T2) (R1, R2, R3)) Func2_3[T1, T2, R1, R2, R3] {
	return func(v1 T1) func(v2 T2) (R1, R2, R3) {
		return func(v2 T2) (R1, R2, R3) {
			return f(v1, v2)
		}
	}
}

type Func3[T1, T2, T3 any] func(v1 T1) func(v2 T2) func(v3 T3)

func (f Func3[T1, T2, T3]) Apply1(v1 T1) Func2[T2, T3] {
	return f(v1)
}

func (f Func3[T1, T2, T3]) Apply2(v1 T1, v2 T2) Func1[T3] {
	return f(v1)(v2)
}

func (f Func3[T1, T2, T3]) Apply3(v1 T1, v2 T2, v3 T3) Func0 {
	return func() {
		f(v1)(v2)(v3)
	}
}

func (f Func3[T1, T2, T3]) Reverse() Func3[T3, T2, T1] {
	return func(v3 T3) func(v2 T2) func(v1 T1) {
		return func(v2 T2) func(v1 T1) {
			return func(v1 T1) {
				f(v1)(v2)(v3)
			}
		}
	}
}

func Make3[T1, T2, T3 any](f func(T1, T2, T3)) Func3[T1, T2, T3] {
	return func(v1 T1) func(v2 T2) func(v3 T3) {
		return func(v2 T2) func(v3 T3) {
			return func(v3 T3) {
				f(v1, v2, v3)
			}
		}
	}
}

type Func3_1[T1, T2, T3, R1 any] func(v1 T1) func(v2 T2) func(v3 T3) R1

func (f Func3_1[T1, T2, T3, R1]) Apply1(v1 T1) Func2_1[T2, T3, R1] {
	return f(v1)
}

func (f Func3_1[T1, T2, T3, R1]) Apply2(v1 T1, v2 T2) Func1_1[T3, R1] {
	return f(v1)(v2)
}

func (f Func3_1[T1, T2, T3, R1]) Apply3(v1 T1, v2 T2, v3 T3) Func0_1[R1] {
	return func() R1 {
		return f(v1)(v2)(v3)
	}
}

func (f Func3_1[T1, T2, T3, R1]) Reverse() Func3_1[T3, T2, T1, R1] {
	return func(v3 T3) func(v2 T2) func(v1 T1) R1 {
		return func(v2 T2) func(v1 T1) R1 {
			return func(v1 T1) R1 {
				return f(v1)(v2)(v3)
			}
		}
	}
}

func Make3to1[T1, T2, T3, R1 any](f func(T1, T2, T3) R1) Func3_1[T1, T2, T3, R1] {
	return func(v1 T1) func(v2 T2) func(v3 T3) R1 {
		return func(v2 T2) func(v3 T3) R1 {
			return func(v3 T3) R1 {
				return f(v1, v2, v3)
			}
		}
	}
}

type Func3_2[T1, T2, T3, R1, R2 any] func(v1 T1) func(v2 T2) func(v3 T3) (R1, R2)

func (f Func3_2[T1, T2, T3, R1, R2]) Apply1(v1 T1) Func2_2[T2, T3, R1, R2] {
	return f(v1)
}

func (f Func3_2[T1, T2, T3, R1, R2]) Apply2(v1 T1, v2 T2) Func1_2[T3, R1, R2] {
	return f(v1)(v2)
}

func (f Func3_2[T1, T2, T3, R1, R2]) Apply3(v1 T1, v2 T2, v3 T3) Func0_2[R1, R2] {
	return func() (R1, R2) {
		return f(v1)(v2)(v3)
	}
}

func (f Func3_2[T1, T2, T3, R1, R2]) Reverse() Func3_2[T3, T2, T1, R1, R2] {
	return func(v3 T3) func(v2 T2) func(v1 T1) (R1, R2) {
		return func(v2 T2) func(v1 T1) (R1, R2) {
			return func(v1 T1) (R1, R2) {
				return f(v1)(v2)(v3)
			}
		}
	}
}

func Make3to2[T1, T2, T3, R1, R2 any](f func(T1, T2, T3) (R1, R2)) Func3_2[T1, T2, T3, R1, R2] {
	return func(v1 T1) func(v2 T2) func(v3 T3) (R1, R2) {
		return func(v2 T2) func(v3 T3) (R1, R2) {
			return func(v3 T3) (R1, R2) {
				return f(v1, v2, v3)
			}
		}
	}
}

type Func3_3[T1, T2, T3, R1, R2, R3 any] func(v1 T1) func(v2 T2) func(v3 T3) (R1, R2, R3)

func (f Func3_3[T1, T2, T3, R1, R2, R3]) Apply1(v1 T1) Func2_3[T2, T3, R1, R2, R3] {
	return f(v1)
}

func (f Func3_3[T1, T2, T3, R1, R2, R3]) Apply2(v1 T1, v2 T2) Func1_3[T3, R1, R2, R3] {
	return f(v1)(v2)
}

func (f Func3_3[T1, T2, T3, R1, R2, R3]) Apply3(v1 T1, v2 T2, v3 T3) Func0_3[R1, R2, R3] {
	return func() (R1, R2, R3) {
		return f(v1)(v2)(v3)
	}
}

func (f Func3_3[T1, T2, T3, R1, R2, R3]) Reverse() Func3_3[T3, T2, T1, R1, R2, R3] {
	return func(v3 T3) func(v2 T2) func(v1 T1) (R1, R2, R3) {
		return func(v2 T2) func(v1 T1) (R1, R2, R3) {
			return func(v1 T1) (R1, R2, R3) {
				return f(v1)(v2)(v3)
			}
		}
	}
}

func Make3to3[T1, T2, T3, R1, R2, R3 any](f func(T1, T2, T3) (R1, R2, R3)) Func3_3[T1, T2, T3, R1, R2, R3] {
	return func(v1 T1) func(v2 T2) func(v3 T3) (R1, R2, R3) {
		return func(v2 T2) func(v3 T3) (R1, R2, R3) {
			return func(v3 T3) (R1, R2, R3) {
				return f(v1, v2, v3)
			}
		}
	}
}
