//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"slices"
	"strings"
	"text/template"
)

var funcs = template.FuncMap{
	"join":    strings.Join,
	"reverse": reverse,
	"concat":  concat,
}

func reverse(a []string) []string {
	b := make([]string, 0, len(a))
	for _, s := range slices.Backward(a) {
		b = append(b, s)
	}
	return b
}

func concat(a, b []string) []string {
	r := make([]string, len(a)+len(b))
	copy(r[:len(a)], a)
	copy(r[len(a):], b)
	return r
}

var mainTemplate = template.Must(template.New("main").Funcs(funcs).Parse(`
{{- define "func" -}}
  {{- if gt (len .Args) 0 -}}
    {{range .Args}} func({{.Name}} {{.Type}}) {{- end -}}
  {{- else -}}
    func()
  {{- end -}}
  {{if gt .NReply 0}} ({{join .Decl.ReplyTypes ", "}}){{- end -}}
{{- end -}}
{{- define "body" -}}
  return {{template "func" .}} {
    {{if .More -}}
      {{template "body" .Next}}
    {{- else -}}
      {{if gt .Decl.Params.NReply 0}}return {{end}}f({{join .Decl.ArgNames ", "}})
    {{- end}}
  }
{{- end -}}
{{- define "func_r" -}}
  {{- if gt (len .Args) 0 -}}
    {{range .ArgsRev}} func({{.Name}} {{.Type}}) {{- end -}}
  {{- else -}}
    func()
  {{- end -}}
  {{if gt .NReply 0}} ({{join .Decl.ReplyTypes ", "}}){{- end -}}
{{- end -}}
{{- define "revbody" -}}
  return {{template "func_r" .}} {
    {{if .More -}}
      {{template "revbody" .Next}}
    {{- else -}}
      {{if gt .Decl.Params.NReply 0}}return {{end -}}
      {{- if gt (len .Decl.Params.Args) 0 -}}
        f{{range .Decl.Params.Args}}({{.Name}}){{end}}
      {{- else -}}
        f()
      {{- end -}}
    {{- end}}
  }
{{- end -}}
// Code generated by template.go DO NOT EDIT.

package currying
{{range .}}
type {{.TypeName}}[{{join (concat .ArgTypes .ReplyTypes) ", "}} any] {{template "func" .Params}}

{{range .Applies -}}
func (f {{.Decl.TypeName}}[
  {{- join (concat .Decl.ArgTypes .Decl.ReplyTypes) ", " -}}
]) Apply{{.N}}(
  {{- range .Args -}}
    {{.Name}} {{.Type}},
  {{- end -}}
) {{.TypeName}}{{if gt (len .TypeParams) 0}}[{{join .TypeParams ", "}}]{{end}} {
	{{- if eq .N .Decl.Params.NArg -}}
	return func() ({{join .Decl.ReplyTypes ", "}}) {
		{{if gt .Decl.Params.NReply 0}}return {{end}}f{{range .Args -}}({{.Name}}){{end}}
	}
	{{- else -}}
	return f{{range .Args -}}({{.Name}}){{end}}
	{{end -}}
}

{{end -}}

func (f {{.TypeName}}[
  {{- join (concat .ArgTypes .ReplyTypes) ", " -}}
]) Reverse() {{.TypeName}}[
  {{- join (concat (reverse .ArgTypes) .ReplyTypes) ", " -}}
] {
	{{template "revbody" .Params}}
}

func Make{{.Params.NArg}}{{if gt .Params.NReply 0}}to{{.Params.NReply}}{{end}}[
  {{- join (concat .ArgTypes .ReplyTypes) ", "}} {{"any" -}}
](f func({{- join .ArgTypes ", "}}) ({{join .ReplyTypes ", "}})) {{.TypeName}}[
  {{- join (concat .ArgTypes .ReplyTypes) ", " -}}
]{
	{{template "body" .Params}}
}
{{end}}
`))

type Decl struct {
	Params Params
}

func NewDecl(narg, nreply int) *Decl {
	var d Decl
	d.Params = Params{
		Decl:   &d,
		NArg:   narg,
		NReply: nreply,
	}
	return &d
}

type Params struct {
	Decl   *Decl
	NArg   int
	NReply int
	Off    int
}

func (p Params) More() bool {
	return p.Off+1 < p.NArg
}

func (p Params) Next() Params {
	return Params{
		Decl:   p.Decl,
		NArg:   p.NArg,
		NReply: p.NReply,
		Off:    p.Off + 1,
	}
}

func (p Params) Pos() int {
	return p.Off + 1
}

func (p Params) args() []Arg {
	a := make([]Arg, p.NArg)
	for i := range a {
		a[i] = Arg{
			Name: fmt.Sprintf("v%d", i+1),
			Type: fmt.Sprintf("T%d", i+1),
		}
	}
	return a
}

func (p Params) Args() []Arg {
	return p.args()[p.Off:]
}

func (p Params) ArgsRev() []Arg {
	a := p.args()
	slices.Reverse(a)
	return a[p.Off:]
}

type Arg struct {
	Name string
	Type string
}

func (p *Decl) TypeName() string {
	if p.Params.NReply > 0 {
		return fmt.Sprintf("Func%d_%d", p.Params.NArg, p.Params.NReply)
	} else {
		return fmt.Sprintf("Func%d", p.Params.NArg)
	}
}

func (p *Decl) ArgTypes() []string {
	a := make([]string, p.Params.NArg)
	for i := range a {
		a[i] = fmt.Sprintf("T%d", i+1)
	}
	return a
}

func (p *Decl) ArgNames() []string {
	a := make([]string, p.Params.NArg)
	for i := range a {
		a[i] = fmt.Sprintf("v%d", i+1)
	}
	return a
}

func (p *Decl) ReplyTypes() []string {
	a := make([]string, p.Params.NReply)
	for i := range a {
		a[i] = fmt.Sprintf("R%d", i+1)
	}
	return a
}

func (p *Decl) Applies() []Apply {
	var a []Apply
	args := p.Params.Args()
	for i := 0; i < p.Params.NArg; i++ {
		a = append(a, Apply{
			Decl: p,
			N:    i + 1,
			Args: args[:i+1],
			Rest: Params{
				Decl:   p,
				NArg:   p.Params.NArg,
				NReply: p.Params.NReply,
				Off:    i + 1,
			},
		})
	}
	return a
}

type Apply struct {
	Decl *Decl
	N    int
	Args []Arg
	Rest Params
}

func (a *Apply) TypeName() string {
	if a.Decl.Params.NReply > 0 {
		return fmt.Sprintf("Func%d_%d", a.Decl.Params.NArg-a.N, a.Decl.Params.NReply)
	} else {
		return fmt.Sprintf("Func%d", a.Decl.Params.NArg-a.N)
	}
}

func (a *Apply) TypeParams() []string {
	a1 := a.Decl.ArgTypes()[a.N:]
	a2 := a.Decl.ReplyTypes()
	r := make([]string, len(a1)+len(a2))
	copy(r[:len(a1)], a1)
	copy(r[len(a1):], a2)
	return r
}

func main() {
	log.SetFlags(0)

	var buf bytes.Buffer
	err := mainTemplate.Execute(&buf, []*Decl{
		/*NewDecl(0, 0),*/ NewDecl(0, 1), NewDecl(0, 2), NewDecl(0, 3),
		NewDecl(1, 0), NewDecl(1, 1), NewDecl(1, 2), NewDecl(1, 3),
		NewDecl(2, 0), NewDecl(2, 1), NewDecl(2, 2), NewDecl(2, 3),
		NewDecl(3, 0), NewDecl(3, 1), NewDecl(3, 2), NewDecl(3, 3),
	})
	if err != nil {
		io.Copy(os.Stderr, &buf)
		log.Fatalln("can't execute main:", err)
	}
	s, err := format.Source(buf.Bytes())
	if err != nil {
		io.Copy(os.Stderr, &buf)
		log.Fatalln("can't format main:", err)
	}

	w, err := os.Create("curry_gen.go")
	if err != nil {
		log.Fatalln("can't create:", err)
	}
	fmt.Fprintf(w, "%s", s)
	if err := w.Sync(); err != nil {
		log.Fatalln("can't write:", err)
	}
	w.Close()
}
